name: Generate CV PDF

on:
  push:
    paths:
      - "docs/cv.md"
      - ".github/workflows/generate-cv-pdf.yml"
      - "docs/template/eisvogel.tex"

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra

      - name: Generate Styled PDF
        run: |
          pandoc docs/cv.md \
            --from markdown \
            --template docs/template/eisvogel.tex \
            --pdf-engine=xelatex \
            -V colorlinks=true \
            -V urlcolor=blue \
            -o docs/cv.pdf

      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/cv.pdf

          git commit -m "Generate styled CV PDF" || echo "No changes"

          git push
